services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: final
    volumes:
      - incidents:/app/incidents
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production

volumes:
  incidents: