services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev-builder
    command: "sleep infinity"
    volumes:
      - ./backend:/app
      - /app/.venv
    ports:
      - "8080:8080"
      - "5000:5000"
      