services:
  camera_opener:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: camera_opener_final
    volumes:
      - incidents:/app/incidents

  opencv_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: opencv_service_final
    volumes:
      - incidents:/app/incidents

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production

volumes:
  incidents: